# ===============================
# DATASOURCE POSTGRESQL
# ===============================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=your_username
quarkus.datasource.password=your_password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/your_database_name

# ===============================
# HIBERNATE ORM
# ===============================
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true