# ===============================
# APPLICATION PROPERTIES
# ===============================
quarkus.http.port=8080

# ===============================
# DATASOURCE POSTGRESQL
# ===============================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=your_username
quarkus.datasource.password=your_password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/your_database

# ===============================
# HIBERNATE ORM
# ===============================
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# ===============================
# REST CLIENT
# ===============================
sentiment-api/mp-rest/url=http://localhost:8000
sentiment-api/mp-rest/scope=jakarta.inject.Singleton